### ISSUE TITLE
About dataset

### ISSUE THREAD

**Issue by chaojiewang94** [facebookresearch/UniK-QA#2]
I wonder if you can release the code of processing procedure to obtain the condensed_relations and condensed_hyper_relations in https://dl.fbaipublicfiles.com/UniK-QA/data.tar.xz

**Comment by ccsasuke** [comment]
Unfortunately that piece of code is no longer retrievable since the work of this paper was done 3 years ago.
However, the processing is very straightforward. 

For instance, for the following "graph" with three relations which contains CVT entities (relations types are omitted for simplicity):
`<entity_A, CVT1>, <CVT1, entity_B>, <CVT1, entity_C>`.

condensed_relations would extract two binary relations while removing CVT1:
`<entity_A, entity_B>, <entity_A, entity_C>`

whereas condensed_hyper_relations would extract a single n-ary (tertiary in this example) relation:
`<entity_A, [entity_B, entity_C]>`

**Comment by chaojiewang94** [comment]
Thanks for your answer, one more question, I wonder how to obtain stagg.neighborhoods in freebase from raw freebase dataset.  And which tutorial you follow to build the serve of freebase. Thanks @ccsasuke

**Comment by ccsasuke** [comment]
@chaojiewang94 The preprocessed freebase data (with neighborhood info extracted from STAGG) was downloaded from the GraftNet repo (https://github.com/haitian-sun/GraftNet/blob/master/preprocessing/run_pipeline).
